### ISSUE TITLE
Transition to ensmallen instead of `mlpack/core/optimizers/`

### ISSUE THREAD

**Issue by rcurtin** [mlpack/models#19]
Some of the models still use mlpack optimizers when instead they should be using ensmallen optimizers.  To fix this we should:

1. Make the CMake configuration for this project search for ensmallen (and download if needed).  We can just use the existing mlpack `CMake/FindEnsmallen.cmake` for this.
2. Instead of including things from `mlpack/core/optimizers/...` we should just include `ensmallen.hpp`.
3. Adapt the code to use `ens::<OptimizerName>` not `mlpack::optimization::<OptimizerName>`.

**Comment by zoq** [comment]
Fixed with #18.
