### ISSUE TITLE
Where to put convert class

### ISSUE THREAD

**Issue by heisenbuug** [mlpack/models#26]
I have implemented a Convert class as per the requirement of the [issue](https://github.com/mlpack/models/issues/22)
In which directory should we put this new code?
[Link](https://github.com/heisenbuug/Dataset_Converter) to my implementation.
Once decided I can make a PR accordingly.

**Comment by kartikdutt18** [comment]
Hey @heisenbuug, Sorry for the late reply. I'm completely forgot about this. What do you thing about having a separate directory like dataset_utils or something.

**Comment by heisenbuug** [comment]
Hey @kartikdutt18 , it's fine. Yea...I think it would totally make sense to do that...I will make a PR accordingly .

**Comment by shrit** [comment]
@kartikdutt18 Do you need to keep this one open? Thanks

**Comment by heisenbuug** [comment]
No, we don't need this one open. Sorry for not updating,
