### ISSUE TITLE
Unknown CMake command "find_package_handle_standard_args"

### ISSUE THREAD

**Issue by evgfreyman** [mlpack/models#3]
Getting an error

> Unknown CMake command "find_package_handle_standard_args"

when trying to use these models for finding MLPack by the following command: `find_package(MLPACK REQUIRED)`.  Tried the latest CMake 3.6

It seems that adding `include(FindPackageHandleStandardArgs)` into beginning of `FindMLPACK.cmake` file solves this issue. I could create a PR for this fix, but I don't have enough expertise in CMake to claim this is a proper solution. So, please confirm that this is ok, and I'll create a PR

**Comment by rcurtin** [comment]
Ah, yeah, find_package_handle_standard_args() has to be made available.  So yeah, just the `include(FindPackageHandleStandardArgs)` should be sufficient.  If you make a PR we can merge it.  Thanks!

**Comment by zoq** [comment]
Fixed in: https://github.com/mlpack/models/pull/4.
