### ISSUE TITLE
Alpha matting model

### ISSUE THREAD

**Issue by Nerdyvedi** [mlpack/models#43]
Alpha matting refers to the problem of extracting foreground from an image. Given an input image, and a trimap, the alpha matting model would extract the foreground.

Would it be of any use if I could add an implementation of [Global sampling based method for Alpha matting](http://mmlab.ie.cuhk.edu.hk/archive/2011/cvpr11matting.pdf)?

I have also written a [blog](https://medium.com/vedacv/paper-summary-a-global-sampling-method-for-alpha-matting-490a4217eb2) that might help in understanding the paper.

**Comment by shrit** [comment]
@Nerdyvedi Please do not hesitate in adding this implementation, all models are welcomed.
