### ISSUE TITLE
Documentation error in augmentation.hpp

### ISSUE THREAD

**Issue by RishabhGarg108** [mlpack/models#44]
While going through the augmentation code, I encountered [this](https://github.com/RishabhGarg108/models/blob/27c481426958b6090ec250a23a0f5cbf3aefeeef/augmentation/augmentation.hpp#L179) line. I am wondering if it should be "the augmentation class should have access ..."?

**Comment by kartikdutt18** [comment]
Right, I gave that access so that when we load images in Object Detection class they can be resized else we can create a matrix for them.

**Comment by RishabhGarg108** [comment]
Sure, I will do it. Thanks for the quick response :-)
