### ISSUE TITLE
Namespace and Include guards 

### ISSUE THREAD

**Issue by Aakash-kaushik** [mlpack/models#54]
Points to Discuss:

1. For now the models repo uses mlpack namespace in some files and just plain nothing in some so should this repository have its namespace in all the files or just carry the mlpack namespace.
2. the include guard in all the files follows a format as MODELS_FILENAME.HPP, I propose that it follows a similar structure such as mlpack which will be MODELS_FOLDER_NAME_FILENAME.HPP.

also please keep in mind that for now this repository doesn't have any installation candidate or place that it is installed in but that will be included in it very soon, I am just figuring out how to configure install with cmake and i will do that then.

**Comment by rcurtin** [comment]
Definitely agreed on both points!  Thanks for bringing it up.  Personally I think it would be fine to put things here in the `mlpack::models` namespace, but whatever we choose is fine.  (It should definitely be in a namespace.)

Good point on the include guards too---I agree with your proposal. :+1:

**Comment by Aakash-kaushik** [comment]
Great, I think `mlpack::models` is fine and i will open a PR soon to include both of these changes.
