### ISSUE TITLE
Improve description for the repository  

### ISSUE THREAD

**Issue by Aakash-kaushik** [mlpack/models#58]
![image](https://user-images.githubusercontent.com/39410692/119276457-fa178280-bc37-11eb-8639-641ad1c99203.png)
So while searching the models repository on google and even when someone comes to take a look they see the description to understand what the repository is about and so after some talk we came up with a simple suggestion to change it to - "Models built with mlpack" 

Let me know your suggestions and feel free to propose something else or vote on it if you like this one.

**Comment by birm** [comment]
I like that, I've changed it at least temporarily

**Comment by rcurtin** [comment]
I think "models built with mlpack" is great and a big improvement. :+1:

**Comment by zoq** [comment]
Thanks for opening the issue, "Models built with mlpack" sounds good to me as well.

**Comment by Aakash-kaushik** [comment]
Thanks everyone, so i will just let this issue be open for a week for anyone else to give their suggestions.

**Comment by Aakash-kaushik** [comment]
![image](https://user-images.githubusercontent.com/39410692/119317683-fdd9f200-bc95-11eb-8c1b-c460fc34ba3d.png)
Just wanted to show this. 
Looks so much better now !

**Comment by Aakash-kaushik** [comment]
Closing this as there isn't much feedback on this.

**Comment by rcurtin** [comment]
Thanks @Aakash-kaushik for driving this effort!  It does look much better now. :+1:
