### ISSUE TITLE
dataloader.LoadImageDatasetFromDirectory can not be used because error impl in Augmentation::ResizeTransform

### ISSUE THREAD

**Issue by peichao538** [mlpack/models#82]

**Comment by rcurtin** [comment]
Can you paste what the actual error is?  I am not very familiar with this code, but I'm happy to try and take a look to see what is wrong and if there is an easy fix.

**Comment by peichao538** [comment]
> Can you paste what the actual error is? I am not very familiar with this code, but I'm happy to try and take a look to see what is wrong and if there is an easy fix.

Augmentation::ResizeTransform use mlpack::BilinearInterpolation to process image data, but mlpack::BilinearInterpolation has not been modified and adapted, so some project cannot be compiled and the function of "dataloader" also can not been used to process image directly. I have changed the code with a simple comment as shown in the pasted below, and have not completely implemented BilinearInterpolationType.

template<typename DatasetType>
void Augmentation::ResizeTransform(
    DatasetType& dataset,
    const size_t datapointWidth,
    const size_t datapointHeight,
    const size_t datapointDepth,
    const std::string& augmentation)
{
  size_t outputWidth = 0, outputHeight = 0;

  // Get output width and output height.
  GetResizeParam(outputWidth, outputHeight, augmentation);

  // We will use mlpack's bilinear interpolation layer to
  // resize the input.
//   mlpack::BilinearInterpolation<DatasetType, DatasetType> resizeLayer(
//       datapointWidth, datapointHeight, outputWidth, outputHeight,
//       datapointDepth);
//   mlpack::BilinearInterpolation<DatasetType, DatasetType> resizeLayer(
//       datapointWidth, datapointHeight, outputWidth, outputHeight,
//       datapointDepth);
    mlpack::BilinearInterpolation resizeLayer(
       outputWidth, outputHeight);

  DatasetType output;
  resizeLayer.Forward(dataset, output);
  dataset = std::move(output);
}
