### ISSUE TITLE
mlpack version specific

### ISSUE THREAD

**Issue by Adarsh97** [mlpack/models#83]
Is the examples given works only for a specific mlpack version? 
If yes please provide the version of mlpack.

**Comment by rcurtin** [comment]
In general the models are meant to work with the latest version of mlpack, but it's always possible that some of the code has gone out of date.  This repository is unfortunately less well-maintained than mlpack or the examples repository.  If you find some code that is out of date or doesn't work, please do feel free to open an issue. :+1:

**Comment by Adarsh97** [comment]
Got it. 
First observation is I am seeing negative loss value while training as well as during evaluate function. 
This is happening when our input is not in 0 to 1 range. 
Is this expected?
